version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: db123
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
  app:
    image: my-node-app
    ports:
      - "1300:3000"
